#!/usr/bin/python3

import subprocess
import os
os.environ["ANSIBLE_STDOUT_CALLBACK"] = "community.general.yaml"

setup_scripts_path="/tmp/setup-scripts/getting-started-mesh/"

# Solve mesh-instance-groups
mesh_instance_groups_solve = subprocess.run(["ansible-playbook", setup_scripts_path+"getting-started-mesh-setup.yml",
                                            "-i", setup_scripts_path+"inventory.ini",
                                            "--tags", "mesh-instance-groups-solve", "-v"])
