---
all:
  children:
    ciservers:
      hosts:
        gitea:
        jenkins:
    automationcontroller:
      hosts:
        controller.acme.example.com:
          ansible_connection: local
    webservers:
      hosts:
        web1.acme.example.com:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/instruqt_lab
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=60s'
    ansible_ssh_pipelining: true
    ansible_host_key_checking: false
    ansible_host: devops-controller
    ansible_user: rhel
