version: "3"
virtualmachines:
- name: devops-controller
  image: instruqt-dev-356115/devops-controller-image
  shell: /bin/su - rhel -s /bin/bash
  environment:
    GITEA_STUDENT_PASSWORD: student
    JENKINS_STUDENT_PASSWORD: student
  machine_type: n1-standard-2
