#!/usr/bin/python3

import subprocess
import os
os.environ["ANSIBLE_STDOUT_CALLBACK"] = "community.general.yaml"

# Vars
setup_scripts_path="/tmp/setup-scripts/getting-started-mesh/"

# Solve high-availability
mesh_ha_solve = subprocess.run(["ansible-playbook", setup_scripts_path+"getting-started-mesh-setup.yml",
                                "-i", setup_scripts_path+"inventory.ini",
                                "--tags", "high-availability-solve"])
