version: "2"
virtualmachines:
- name: mesh-exec1
  image: red-hat-mbu/mesh-node
  shell: /bin/su - rhel -s /bin/bash
  environment:
    TERM: XTERM
  machine_type: n1-standard-1
- name: mesh-hybrid1
  image: red-hat-mbu/mesh-hybrid1
  shell: /bin/su - rhel -s /bin/bash
  environment:
    TERM: XTERM
  machine_type: n1-standard-2
