#!/bin/python3

import subprocess
import os
import yaml
from shlex import quote, join
os.environ["ANSIBLE_STDOUT_CALLBACK"] = "community.general.yaml"

# Load extra_vars.yml
extra_vars_file = open("/tmp/setup-scripts/getting-started-mesh/extra_vars.yml")
parsed_extra_vars_file = yaml.load(extra_vars_file, yaml.loader.FullLoader)

# Generate controller oauth token
auth_token = subprocess.run(["ansible-playbook", "/tmp/setup-scripts/getting-started-mesh/getting-started-mesh-setup.yml", "-e", "@/tmp/setup-scripts/getting-started-mesh/extra_vars.yml", "--tags", "auth-token"])

# Check instance groups are assigned to inventories
for key,val in parsed_extra_vars_file.items(): 
    if key == "lab_inventories":
        for inventory in parsed_extra_vars_file[key]:
            inv_instance_groups_str = ','.join(key for key in inventory["inv_instance_groups"])
            lab_inv_igs_output = subprocess.run(["ansible-playbook", "/tmp/setup-scripts/getting-started-mesh/getting-started-mesh-setup.yml", "-e", "lab_inv_name="+quote(inventory["name"]), "-e", "lab_inv_igs="+quote(inv_instance_groups_str), "-e", "@/tmp/setup-scripts/getting-started-mesh/extra_vars.yml", "--tags", "multi-site-check-inv-ig"])
            if lab_inv_igs_output.returncode > 0:
                print ( "FAIL: Please make sure the " + inv_instance_groups_str + " instance group(s) is associated with the " + inventory["name"] + " inventory and no incorrect instance groups are assigned." )
                exit(1)
    # Check lab job templates used correct inventories
    if key == "lab_job_templates":
        for job_template in parsed_extra_vars_file[key]:
            for inventory in parsed_extra_vars_file["lab_inventories"]:
                lab_inv_jt_output = subprocess.run(["ansible-playbook", "/tmp/setup-scripts/getting-started-mesh/getting-started-mesh-setup.yml", "-e", "lab_inv_name="+quote(inventory["name"]), "-e", "lab_jt_name="+quote(job_template["jt_name"]), "-e", "@/tmp/setup-scripts/getting-started-mesh/extra_vars.yml", "--tags", "multi-site-check-inv-jt"])
                if lab_inv_jt_output.returncode > 0:
                    print ( "FAIL: Please make sure you've run the " + job_template["jt_name"] + " job template using the " + inventory["name"] + " inventory." )
                    exit(1)