#!/bin/bash
set -euxo pipefail

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

# Setup Instruqt user SSH keys
for user in rhel
do 
    cp -a /root/.ssh/* /home/"${user}"/.ssh/
    chown -R "${user}":"${user}" /home/"${user}"/.ssh
done

# Remove student private SSH keys
# for key in id_rsa instruqt_lab
# do 
#     rm ~"${STUDENT_USERNAME}"/.ssh/"${key}"
# done

# Update containers
/bin/podman auto-update

# ~/.{{ track_slug }}_ansible_vault_password
# Testing Get instruqt lab content
/usr/bin/aws s3 sync --no-sign-request s3://tmm-instruqt-content.demoredhat.com.private/lightspeed-101 /opt/setup-scripts/lightspeed-101
# ansible-playbook /opt/setup-scripts/devops-controller/setup-devops-controller.yml -i /opt/setup-scripts/devops-controller/inventory.ini --tags configure-repo

cd /opt/setup-scripts/lightspeed-101/setup/
ln ~root/.lightspeed-101_ansible_vault_password .lightspeed-101_ansible_vault_password
export ANSIBLE_VAULT_PASSWORD_FILE=.lightspeed-101_ansible_vault_password
# ansible-navigator run /opt/setup-scripts/lightspeed-101/setup/lightspeed-101-lab_setup.yml --tags env --mode stdout -vvv
