#!/usr/bin/env python3

import subprocess
import yaml
from shlex import quote
import os


os.environ["ANSIBLE_VAULT_PASSWORD_FILE"] = ".lightspeed-101_ansible_vault_password"
setup_scripts_path="/opt/setup-scripts/lightspeed-101/setup/"

# Change working dir
os.chdir(setup_scripts_path)
# Load extra_vars.yml
extra_vars_file = open("/opt/setup-scripts/lightspeed-101/setup/vars/track_vars.yml")
parsed_extra_vars_file = yaml.load(extra_vars_file, yaml.loader.FullLoader)

# Solve controller-approval
for key,val in parsed_extra_vars_file.items(): 
    if key == "external_content":
        for playbook in parsed_extra_vars_file[key]["playbooks"]:
            setup_generate_tasks = subprocess.run(["ansible-navigator", "run",
                                            setup_scripts_path + "lightspeed-101-lab_setup.yml", 
                                            "-e", "init_playbook_name="+quote(playbook),
                                            "--tags", "setup-external-content-playbooks",
                                            "--mode", "stdout"])
        for jt_name in parsed_extra_vars_file[key]["jt_names"]:
            setup_generate_tasks = subprocess.run(["ansible-navigator", "run",
                                            setup_scripts_path + "lightspeed-101-lab_setup.yml", 
                                            "-e", "jt_name="+quote(jt_name),
                                            "--tags", "setup-external-content-jt",
                                            "--mode", "stdout"])
