---
### Challenge Tasks
# TASK 1
# # 1a. Uncomment Task 1 description and generate a task suggestion.
# TASK 2
# # 2a. Uncomment task description below and generate a task suggestion.
# TASK 3
# 3a. Save your changes.

- name: Configure firewall
  hosts: appservers
  become: true

  vars:
    firewall:
      - permanent: true
        state: enabled
        port: 8065/tcp

  tasks:
    # TASK 1
    # # 1a. Uncomment task description below and generate a task suggestion.

    - name: Include redhat.rhel_system_roles.firewall
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.firewall
      when: ansible_os_family == "RedHat"

    # TASK 2
    # # 2a. Uncomment task description below and generate a task suggestion.

    - name: Run command "podman network reload mattermost-preview" and register result
      ansible.builtin.command:
        cmd: podman network reload mattermost-preview
      register: podman_network_reload_result
      changed_when: podman_network_reload_result.stdout is search("Running")
