#!/bin/bash

while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

# Setup rhel user
cp -a /root/.ssh/* /home/rhel/.ssh/.
chown -R rhel:rhel /home/rhel/.ssh

#Switch to correct Python version
/usr/sbin/alternatives --set python3 /usr/bin/python3.8

# Get playbook from repo
mkdir /tmp/setup-scripts/getting-started-mesh
/usr/bin/curl https://raw.githubusercontent.com/craig-br/instruqt-tracks/devel/setup-scripts/getting-started-mesh/getting-started-mesh-setup.yml -o /tmp/setup-scripts/getting-started-mesh/getting-started-mesh-setup.yml

# Use playbook to setup environment
/bin/ansible-playbook /tmp/setup-scripts/getting-started-mesh/getting-started-mesh-setup.yml --tags setup-env