#!/bin/bash

while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

# Setup rhel user
cp -a /root/.ssh/* /home/rhel/.ssh/.
chown -R rhel:rhel /home/rhel/.ssh

#Switch to correct Python version
/usr/sbin/alternatives --set python3 /usr/bin/python3.8

# Clear history
/bin/su - rhel -c "cat /dev/null > ~/.bash_history; history -c"